
[package]
name = "terminal-multisig"
version = "2.1.0"
description = "An SDK for building automated programs on Solana"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://squads.so"
authors = ["Valentin Madrid <valentin@incility.com>"]
documentation = "https://developers.terminal.so"

[lib]
name = "terminal_multisig"

[dependencies]
futures = { version = "0.3.28" , features = ["async-await", "alloc"] }
solana-client = "1.17.4"
thiserror = "1.0.48"

[features]
default = []
